# Generated by Django 4.2.1 on 2023-08-22 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreMembers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembers',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
